### ISSUE TITLE
Windows install of 1.0 does not work

### ISSUE THREAD

**Issue by nitmws** [ZettelGeist/zettelgeist#3]
I've installed Zettelgeist on Windows 10 (1709) by `pip install zettelgeist`
This resulted in  `Successfully installed tatsu-4.2.5 zettelgeist-1.0`

But when calling any zettel command from the command line I see this error message:
```
Traceback (most recent call last):
  File "c:\programmediv\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programmediv\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgrammeDiv\Python35\Scripts\zettel.exe\__main__.py", line 5, in <module>
  File "c:\programmediv\python35\lib\site-packages\zettelgeist\zettel.py", line 7, in <module>
    import readline  # for input()
ImportError: No module named 'readline'

```

**Comment by gkthiruvathukal** [comment]
@nitmws Are you installing this with regular Windows Python or via python in Windows Subsystem for Linux? At this time, we're not supporting native Windows, only WSL.

**Comment by gkthiruvathukal** [comment]
@nitmws  I'm guessing you might have moved beyond ZettelGeist, but if you are still interested, we have been running ZettelGeist since Windows Subsystem for Linux version 1. It also works on version 2.
